build:
	trunk build --config dev/Trunk.toml

serve:
	trunk serve --config dev/Trunk.toml

	
dist:
	trunk build --config release/Trunk.toml




RELEASE_TAG = v0.1.0

release:
	gh release create $(RELEASE_TAG)